### ISSUE TITLE
制作的时候有问题

### ISSUE THREAD

**Issue by redapple0204** [Wuxiangdong/Archiso#1]
>passwd: password expiry information changed.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  895k  100  895k    0     0  91064      0  0:00:10  0:00:10 --:--:--  132k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  753k  100  753k    0     0  79390      0  0:00:09  0:00:09 --:--:-- 48447
mkfs.fat 4.0 (2016-05-06)
cp: error writing 'work/efiboot/EFI/archiso/archiso.img': No space left on device

**Comment by redapple0204** [comment]
>redapple@arch ~/Archiso> df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             485M     0  485M   0% /dev
run             490M  1.5M  488M   1% /run
/dev/sda2        98G  3.6G   89G   4% /
tmpfs           490M     0  490M   0% /dev/shm
tmpfs           490M     0  490M   0% /sys/fs/cgroup
tmpfs           490M     0  490M   0% /tmp
tmpfs            98M     0   98M   0% /run/user/1000
tmpfs            98M     0   98M   0% /run/user/0
/dev/loop0       40M   40M     0 100% /root/Archiso/work/efiboot
redapple@arch ~/Archiso>

**Comment by Psi57** [comment]
收到，我看下，，，

**Comment by redapple0204** [comment]
@Wuxiangdong 好的，谢谢先

**Comment by Psi57** [comment]
我电脑风扇坏了QAQ
大概只能初七以后看看

**Comment by redapple0204** [comment]
好吧....

**Comment by Psi57** [comment]
我看了下
在build.sh  173行附近
Archiso好像把40M改成了64M

我现在试试能不能构建

**Comment by redapple0204** [comment]
@Wuxiangdong 当时我看到有社区有人说改成45M，然而挂载还是40M

**Comment by Psi57** [comment]
我成功了，，

**Comment by Psi57** [comment]
改成64M

**Comment by Psi57** [comment]
试试新的commit

**Comment by redapple0204** [comment]
@Wuxiangdong 好啦，thx。
说实话我是第一次遇到那么负责的项目负责人...
一般人都是不理会的

**Comment by redapple0204** [comment]
@Wuxiangdong 顺便问下能不能修改生成后的live中的大小
默认的200多m装几个东西就没了

**Comment by Psi57** [comment]
你是指像Ubuntu的功能吧？
这个没有研究过，，，

**Comment by redapple0204** [comment]
@Wuxiangdong 我说制作完成后的archlive可用空间太少了！！
![7](https://cloud.githubusercontent.com/assets/16254644/22612953/3170d6d2-eaaf-11e6-9907-5103c79744d3.PNG)

**Comment by Psi57** [comment]
关于怎么扩容我不知道<(=￣▽￣=)>

**Comment by Psi57** [comment]
我在https://git.archlinux.org/archiso.git/tree/docs/README.bootparams
找到一个选项
* cow_spacesize=    Set the size for COW space (tmpfs). Valid for both
                    dm-snapshot and overlayfs mode.
                    The argument is an integer and optional unit.
                    Units are M,G (powers of 1024).
                    Default: "256M"
但我不知到对不对啊

**Comment by redapple0204** [comment]
@Wuxiangdong 应该是吧，我看看

**Comment by Psi57** [comment]
我不知道怎么用<(=￣▽￣=)>

**Comment by redapple0204** [comment]
@Wuxiangdong 忽然看了下我也不会用啊==
我去开个issue算了

**Comment by redapple0204** [comment]
等等，这不是github==
