### ISSUE TITLE
建议改下pacman.conf

### ISSUE THREAD

**Issue by redapple0204** [Wuxiangdong/Archiso#2]
建议注释这三行，因为这个服务器指向了本地==
导致制作的时候翻车
>[customrepo]
SigLevel = Never
Server = file:///home/wuxiangdong/extra/archlive/customrepo/$arch

**Comment by Psi57** [comment]
这个repo好像没发到github上的样子Σ<(=⊙▽⊙)"
这个repo有两个从AUR里来的applet
我试试能不能用相对路径<(=￣▽￣=)>

**Comment by Psi57** [comment]
用不了相对路径
所以我把两个本地包解压了

**Comment by redapple0204** [comment]
@Wuxiangdong 好吧，这配置文档真鸡肋..>

**Comment by Psi57** [comment]
<(=╯▽╰=)>
