### ISSUE TITLE
楼主，我可以把构建的iso发到贴吧里吗？

### ISSUE THREAD

**Issue by lsblk** [Wuxiangdong/Archiso#3]

**Comment by lsblk** [comment]
不对其进行任何改动

**Comment by Psi57** [comment]
可以

**Comment by Psi57** [comment]
把帖子地址给我下:)

**Comment by lsblk** [comment]
楼主，抱歉来晚了，因为太懒iso一直没有制作和上传，这次我做好了以后发现su切换root需要密码，直接按回车会提示鉴定失败，sudo也没法用提示sudoers文件没有用户信息，所以现在无法使用超级用户了，怎么破？

**Comment by Psi57** [comment]
我在构建前把sudoers文件准备好 :)
至于su的话，可以sudo su来解决
也可以直接alias "su" "sudo su"

**Comment by lsblk** [comment]
http://imgsrc.baidu.com/forum/w%3D580%3Bcp%3Dtieba%2C10%2C468%3Bap%3D%CD%F5%C6%D5%D6%DE%B0%C9%2C90%2C476/sign=f606d52cfe03918fd7d13dc2610645e7/0ad942dde71190efe3e71013c71b9d16fffa60cf.jpg 这是错误情况，我添加了sudo也没用

**Comment by Psi57** [comment]
sudoers 应属于 root ，复制的时候应该用root权限复制
在ArchWiki上也有

>  It is recommended to act as root in all the following steps. If not, it is very likely to have problems with false permissions later.


这几天有点忙，回复晚了一点，，，

**Comment by lsblk** [comment]
已经发在了你的帖子里了，，，，就是archlinux吧的精品贴

**Comment by Psi57** [comment]
哦，好的:)
